name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run services
      run: docker compose up -d --build

    - name: Wait for services to be healthy (optional, but good practice)
      # In a real app, you might have healthchecks in docker-compose
      run: sleep 10 # Simple wait, replace with proper healthcheck wait in the future

    - name: Run smoke test
      run: docker compose run --rm backend python /app/tests/smoke_test.py

    - name: Stop services
      run: docker compose down 